#!/usr/bin/env node
/**
 * Generates the two secrets this project needs and writes them into `.env`,
 * creating it from `.env.example` on first run.
 *
 * Existing non-empty values are never overwritten — regenerating
 * N8N_ENCRYPTION_KEY after credentials are saved would make every stored
 * Google/Anthropic credential permanently undecryptable.
 */
import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync, chmodSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const envPath = join(root, ".env");
const examplePath = join(root, ".env.example");

if (!existsSync(envPath)) {
  if (!existsSync(examplePath)) {
    console.error("Missing .env.example — cannot bootstrap .env");
    process.exit(1);
  }
  writeFileSync(envPath, readFileSync(examplePath, "utf8"), { mode: 0o600 });
  console.log("Created .env from .env.example");
}

let env = readFileSync(envPath, "utf8");

/** Fill `KEY=` only when it is currently empty. Returns true if it wrote. */
function fillIfEmpty(key, value) {
  const line = new RegExp(`^${key}=(.*)$`, "m");
  const match = env.match(line);

  if (!match) {
    env += `${env.endsWith("\n") ? "" : "\n"}${key}=${value}\n`;
    return true;
  }
  if (match[1].trim() !== "") {
    console.log(`  ${key} already set — left untouched`);
    return false;
  }
  env = env.replace(line, `${key}=${value}`);
  return true;
}

const wrote = [
  fillIfEmpty("N8N_ENCRYPTION_KEY", randomBytes(32).toString("base64")),
  fillIfEmpty("INGEST_TOKEN", randomBytes(32).toString("hex")),
].some(Boolean);

if (wrote) {
  writeFileSync(envPath, env, { mode: 0o600 });
  console.log("Wrote secrets to .env");
}

// Best-effort permission tightening. A no-op on Windows, where ACLs govern.
try {
  chmodSync(envPath, 0o600);
} catch {
  /* non-POSIX filesystem */
}

/*
 * Next.js only reads .env files from its own directory — the root .env is
 * invisible to it. Mirror the handful of keys the web app needs into
 * web/.env.local so `npm run web:dev` works without exporting anything by
 * hand. Regenerated every run so the two files cannot drift apart.
 */
function readKey(name) {
  const match = env.match(new RegExp(`^${name}=(.*)$`, "m"));
  return match ? match[1].trim() : "";
}

const webEnvPath = join(root, "web", ".env.local");
const webKeys = [
  "N8N_WEBHOOK_URL",
  "INGEST_TOKEN",
  "MAX_UPLOAD_MB",
];

const webEnv = [
  "# Generated by scripts/gen-secrets.mjs — do not edit by hand.",
  "# Mirrors the web-facing keys from the root .env. Re-run `npm run gen:secrets`",
  "# after changing them there.",
  "",
  ...webKeys.map((k) => `${k}=${readKey(k)}`),
  "",
].join("\n");

writeFileSync(webEnvPath, webEnv, { mode: 0o600 });
console.log("Synced web/.env.local for the Next.js app");

console.log("\nDone. `.env` and `web/.env.local` are gitignored — do not commit them.");
